receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: ""

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
