providers = ["node"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node --no-deprecation dist/index.js"

[variables]
NODE_OPTIONS = "--no-deprecation"
