<#
Interactive helper to create local .env files for Supabase + Twilio.
Run from project root in PowerShell: `./scripts/configure-twilio-supabase.ps1`

This writes a project `.env` and `server/.env.local` (overwrite if present).
Do NOT commit the generated files to git.
#>

function Read-Secret([string]$prompt) {
    Write-Host -NoNewline "$prompt: "
    $sec = Read-Host -AsSecureString
    return [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}

Write-Host "--- Supabase & Twilio local config helper ---"

$viteUrl = Read-Host "VITE_SUPABASE_URL (e.g. https://xxx.supabase.co)"
$viteKey = Read-Host "VITE_SUPABASE_ANON_KEY"
$authRedirect = Read-Host "VITE_AUTH_REDIRECT_URL (optional)"
$siteUrl = Read-Host "VITE_SITE_URL (optional)"

$supabaseUrl = Read-Host "SUPABASE_URL (service URL, e.g. https://xxx.supabase.co)"
$supabaseServiceKey = Read-Secret "SUPABASE_SERVICE_ROLE_KEY (secret)"

Write-Host "--- Google / Facebook OAuth ---"
$googleClientId = Read-Host "SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID"
$googleSecret = Read-Secret "SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET (secret)"
$facebookClientId = Read-Host "SUPABASE_AUTH_EXTERNAL_FACEBOOK_CLIENT_ID"
$facebookSecret = Read-Secret "SUPABASE_AUTH_EXTERNAL_FACEBOOK_SECRET (secret)"

Write-Host "--- Twilio ---"
$twilioAccountSid = Read-Host "TWILIO_ACCOUNT_SID"
$twilioAuthToken = Read-Secret "TWILIO_AUTH_TOKEN (secret)"
$twilioMessagingServiceSid = Read-Host "TWILIO_MESSAGING_SERVICE_SID (optional, MG...)"
$twilioVerifyServiceSid = Read-Host "TWILIO_VERIFY_SERVICE_SID (optional, VA...)"
$twilioPhoneNumber = Read-Host "TWILIO_PHONE_NUMBER (optional, +48...)"

Write-Host "Writing .env (root) and server/.env.local ..."

$envContent = @"
# Local environment - generated by scripts/configure-twilio-supabase.ps1

VITE_SUPABASE_URL=$viteUrl
VITE_SUPABASE_ANON_KEY=$viteKey
VITE_AUTH_REDIRECT_URL=$authRedirect
VITE_SITE_URL=$siteUrl

SUPABASE_URL=$supabaseUrl
SUPABASE_SERVICE_ROLE_KEY=$supabaseServiceKey

SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID=$googleClientId
SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET=$googleSecret
SUPABASE_AUTH_EXTERNAL_FACEBOOK_CLIENT_ID=$facebookClientId
SUPABASE_AUTH_EXTERNAL_FACEBOOK_SECRET=$facebookSecret

SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN=$twilioAuthToken

TWILIO_ACCOUNT_SID=$twilioAccountSid
TWILIO_AUTH_TOKEN=$twilioAuthToken
TWILIO_MESSAGING_SERVICE_SID=$twilioMessagingServiceSid
TWILIO_VERIFY_SERVICE_SID=$twilioVerifyServiceSid
TWILIO_PHONE_NUMBER=$twilioPhoneNumber

CLIENT_URL=http://localhost:5173
NODE_ENV=development
"@

$rootEnvPath = Join-Path -Path (Get-Location) -ChildPath '.env'
[System.IO.File]::WriteAllText($rootEnvPath, $envContent)
Write-Host ".env written to $rootEnvPath"

$serverEnvContent = @"
# server/.env.local - generated by scripts/configure-twilio-supabase.ps1
SUPABASE_URL=$supabaseUrl
SUPABASE_SERVICE_ROLE_KEY=$supabaseServiceKey

SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID=$googleClientId
SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET=$googleSecret
SUPABASE_AUTH_EXTERNAL_FACEBOOK_CLIENT_ID=$facebookClientId
SUPABASE_AUTH_EXTERNAL_FACEBOOK_SECRET=$facebookSecret

TWILIO_ACCOUNT_SID=$twilioAccountSid
TWILIO_AUTH_TOKEN=$twilioAuthToken
TWILIO_MESSAGING_SERVICE_SID=$twilioMessagingServiceSid
TWILIO_VERIFY_SERVICE_SID=$twilioVerifyServiceSid
TWILIO_PHONE_NUMBER=$twilioPhoneNumber

CLIENT_URL=http://localhost:5173
PORT=8000
NODE_ENV=development
DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres
"@

$serverEnvPath = Join-Path -Path (Get-Location) -ChildPath 'server\.env.local'
[System.IO.File]::WriteAllText($serverEnvPath, $serverEnvContent)
Write-Host "server/.env.local written to $serverEnvPath"

Write-Host ""
Write-Host "Next steps (run in PowerShell):"
Write-Host "  1) Start Supabase local services: `npx supabase start`"
Write-Host "  2) Ensure SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN is available to Supabase CLI (export in same shell):"
Write-Host "       $env:SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN = '$twilioAuthToken'"
Write-Host "  3) Register OAuth callbacks in Google/Facebook using Supabase API URL:"
Write-Host "       Allowed redirect/callback: http://127.0.0.1:54321/auth/v1/callback"
Write-Host "       Post-auth redirect allowlist: http://localhost:5173 and http://localhost:5173/auth"
Write-Host "  3) Start your API server: (cd server; npm install; npm run dev)"
Write-Host "  4) Expose server via ngrok: `npx ngrok http 8000` and set Twilio webhook to https://<NGROK>/api/twilio/incoming"
Write-Host "  5) (Optional) Create Messaging Service in Twilio Console and set TWILIO_MESSAGING_SERVICE_SID"

Write-Host "IMPORTANT: .env and server/.env.local contain secrets. Do not commit them to git."
